### PR TITLE
Validate AwsSigner with 'AWS Signature Version 4 Test Suite'

### PR DESCRIPTION
**Pull request by marko-asplund**
Currently, the test cases zip file needs to be downloaded and extracted separately.
A better approach would be to take the `.req` and `.authz` files and place them in `resources in `modules/auth/src/main/resources`. Looking forward to hearing about your feedback on this.

Also, currently 15 test cases are failing, 16 succeed. Need to analyse the failures to see if they're caused by test code errors or something else.

### CODE REVIEW

**Comment by filosganga** [comment]
Hi,
Thank you so much for your effort.

I believe that putting the `.req` and `.authz` files under the `test/resources` folder is the way to go, at least for the moment.

Regarding the failures, the current auth approach has been only tested on features that we use, so probably there are few holes here and there. Worth notice, that the AWS suite does not cover all the possible scenario as well. For example, we had a few issues regarding the S3 path handling in the signature.

**Comment by marko-asplund** [comment]
@filosganga Thanks for the feedback! I'll add the test case files in `test/resources` and update the PR 👍

Also, I've been analysing the failures and it seems that some of the failures are caused by `AwsSigner` request canonicalization and some also by http4s uri parsing. I'll continue analysing some of the remaining error cases.

**Comment by marko-asplund** [comment]
@filosganga PR updated to include files from the test suite.
Several test cases are still failing, but based on my analysis so far, at least some of them fail due to canonicalization issues with `AwsSigner`.

Is this PR something you could consider merging?
If yes, is there something I can still do?

**Comment by marko-asplund** [comment]
@filosganga Have you had a chance to review this PR in detail?

**Comment by filosganga** [comment]
Thanks @marko-asplund

**Pull request merged**
